# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import stateless_pb2 as stateless__pb2


class StatelessNumberGeneratorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GenerateSequence = channel.unary_stream(
        '/ablyStatelessServer.StatelessNumberGenerator/GenerateSequence',
        request_serializer=stateless__pb2.GenerateSequenceRequest.SerializeToString,
        response_deserializer=stateless__pb2.Generated.FromString,
        )


class StatelessNumberGeneratorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GenerateSequence(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StatelessNumberGeneratorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GenerateSequence': grpc.unary_stream_rpc_method_handler(
          servicer.GenerateSequence,
          request_deserializer=stateless__pb2.GenerateSequenceRequest.FromString,
          response_serializer=stateless__pb2.Generated.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ablyStatelessServer.StatelessNumberGenerator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
