# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import stateful_pb2 as stateful__pb2


class StatefulNumberGeneratorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GenerateSequence = channel.unary_stream(
        '/ablyStatefulServer.StatefulNumberGenerator/GenerateSequence',
        request_serializer=stateful__pb2.GenerateSequenceRequest.SerializeToString,
        response_deserializer=stateful__pb2.Generated.FromString,
        )
    self.ReconnectSequence = channel.unary_stream(
        '/ablyStatefulServer.StatefulNumberGenerator/ReconnectSequence',
        request_serializer=stateful__pb2.ReconnectSequenceRequest.SerializeToString,
        response_deserializer=stateful__pb2.Generated.FromString,
        )


class StatefulNumberGeneratorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GenerateSequence(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReconnectSequence(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StatefulNumberGeneratorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GenerateSequence': grpc.unary_stream_rpc_method_handler(
          servicer.GenerateSequence,
          request_deserializer=stateful__pb2.GenerateSequenceRequest.FromString,
          response_serializer=stateful__pb2.Generated.SerializeToString,
      ),
      'ReconnectSequence': grpc.unary_stream_rpc_method_handler(
          servicer.ReconnectSequence,
          request_deserializer=stateful__pb2.ReconnectSequenceRequest.FromString,
          response_serializer=stateful__pb2.Generated.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ablyStatefulServer.StatefulNumberGenerator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
