# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stateless.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stateless.proto',
  package='ablyStatelessServer',
  syntax='proto3',
  serialized_options=_b('Z\005proto'),
  serialized_pb=_b('\n\x0fstateless.proto\x12\x13\x61\x62lyStatelessServer\".\n\x17GenerateSequenceRequest\x12\x13\n\x0brestartFrom\x18\x01 \x01(\r\"\x1b\n\tGenerated\x12\x0e\n\x06number\x18\x01 \x01(\r2~\n\x18StatelessNumberGenerator\x12\x62\n\x10GenerateSequence\x12,.ablyStatelessServer.GenerateSequenceRequest\x1a\x1e.ablyStatelessServer.Generated0\x01\x42\x07Z\x05protob\x06proto3')
)




_GENERATESEQUENCEREQUEST = _descriptor.Descriptor(
  name='GenerateSequenceRequest',
  full_name='ablyStatelessServer.GenerateSequenceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='restartFrom', full_name='ablyStatelessServer.GenerateSequenceRequest.restartFrom', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=86,
)


_GENERATED = _descriptor.Descriptor(
  name='Generated',
  full_name='ablyStatelessServer.Generated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='ablyStatelessServer.Generated.number', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['GenerateSequenceRequest'] = _GENERATESEQUENCEREQUEST
DESCRIPTOR.message_types_by_name['Generated'] = _GENERATED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenerateSequenceRequest = _reflection.GeneratedProtocolMessageType('GenerateSequenceRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENERATESEQUENCEREQUEST,
  '__module__' : 'stateless_pb2'
  # @@protoc_insertion_point(class_scope:ablyStatelessServer.GenerateSequenceRequest)
  })
_sym_db.RegisterMessage(GenerateSequenceRequest)

Generated = _reflection.GeneratedProtocolMessageType('Generated', (_message.Message,), {
  'DESCRIPTOR' : _GENERATED,
  '__module__' : 'stateless_pb2'
  # @@protoc_insertion_point(class_scope:ablyStatelessServer.Generated)
  })
_sym_db.RegisterMessage(Generated)


DESCRIPTOR._options = None

_STATELESSNUMBERGENERATOR = _descriptor.ServiceDescriptor(
  name='StatelessNumberGenerator',
  full_name='ablyStatelessServer.StatelessNumberGenerator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=117,
  serialized_end=243,
  methods=[
  _descriptor.MethodDescriptor(
    name='GenerateSequence',
    full_name='ablyStatelessServer.StatelessNumberGenerator.GenerateSequence',
    index=0,
    containing_service=None,
    input_type=_GENERATESEQUENCEREQUEST,
    output_type=_GENERATED,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STATELESSNUMBERGENERATOR)

DESCRIPTOR.services_by_name['StatelessNumberGenerator'] = _STATELESSNUMBERGENERATOR

# @@protoc_insertion_point(module_scope)
