# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stateful.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stateful.proto',
  package='ablyStatefulServer',
  syntax='proto3',
  serialized_options=_b('Z\005proto'),
  serialized_pb=_b('\n\x0estateful.proto\x12\x12\x61\x62lyStatefulServer\"G\n\x17GenerateSequenceRequest\x12\x14\n\x0c\x63onnectionID\x18\x01 \x01(\t\x12\x16\n\x0esequenceLength\x18\x02 \x01(\r\"K\n\x18ReconnectSequenceRequest\x12\x14\n\x0c\x63onnectionID\x18\x01 \x01(\t\x12\x19\n\x11lastReceivedIndex\x18\x02 \x01(\r\"@\n\tGenerated\x12\x0e\n\x06number\x18\x01 \x01(\r\x12\x11\n\tfinalItem\x18\x02 \x01(\x08\x12\x10\n\x08\x63hecksum\x18\x03 \x01(\x0c\x32\xdf\x01\n\x17StatefulNumberGenerator\x12`\n\x10GenerateSequence\x12+.ablyStatefulServer.GenerateSequenceRequest\x1a\x1d.ablyStatefulServer.Generated0\x01\x12\x62\n\x11ReconnectSequence\x12,.ablyStatefulServer.ReconnectSequenceRequest\x1a\x1d.ablyStatefulServer.Generated0\x01\x42\x07Z\x05protob\x06proto3')
)




_GENERATESEQUENCEREQUEST = _descriptor.Descriptor(
  name='GenerateSequenceRequest',
  full_name='ablyStatefulServer.GenerateSequenceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='connectionID', full_name='ablyStatefulServer.GenerateSequenceRequest.connectionID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequenceLength', full_name='ablyStatefulServer.GenerateSequenceRequest.sequenceLength', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=109,
)


_RECONNECTSEQUENCEREQUEST = _descriptor.Descriptor(
  name='ReconnectSequenceRequest',
  full_name='ablyStatefulServer.ReconnectSequenceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='connectionID', full_name='ablyStatefulServer.ReconnectSequenceRequest.connectionID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastReceivedIndex', full_name='ablyStatefulServer.ReconnectSequenceRequest.lastReceivedIndex', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=186,
)


_GENERATED = _descriptor.Descriptor(
  name='Generated',
  full_name='ablyStatefulServer.Generated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='ablyStatefulServer.Generated.number', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='finalItem', full_name='ablyStatefulServer.Generated.finalItem', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='checksum', full_name='ablyStatefulServer.Generated.checksum', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=252,
)

DESCRIPTOR.message_types_by_name['GenerateSequenceRequest'] = _GENERATESEQUENCEREQUEST
DESCRIPTOR.message_types_by_name['ReconnectSequenceRequest'] = _RECONNECTSEQUENCEREQUEST
DESCRIPTOR.message_types_by_name['Generated'] = _GENERATED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenerateSequenceRequest = _reflection.GeneratedProtocolMessageType('GenerateSequenceRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENERATESEQUENCEREQUEST,
  '__module__' : 'stateful_pb2'
  # @@protoc_insertion_point(class_scope:ablyStatefulServer.GenerateSequenceRequest)
  })
_sym_db.RegisterMessage(GenerateSequenceRequest)

ReconnectSequenceRequest = _reflection.GeneratedProtocolMessageType('ReconnectSequenceRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECONNECTSEQUENCEREQUEST,
  '__module__' : 'stateful_pb2'
  # @@protoc_insertion_point(class_scope:ablyStatefulServer.ReconnectSequenceRequest)
  })
_sym_db.RegisterMessage(ReconnectSequenceRequest)

Generated = _reflection.GeneratedProtocolMessageType('Generated', (_message.Message,), {
  'DESCRIPTOR' : _GENERATED,
  '__module__' : 'stateful_pb2'
  # @@protoc_insertion_point(class_scope:ablyStatefulServer.Generated)
  })
_sym_db.RegisterMessage(Generated)


DESCRIPTOR._options = None

_STATEFULNUMBERGENERATOR = _descriptor.ServiceDescriptor(
  name='StatefulNumberGenerator',
  full_name='ablyStatefulServer.StatefulNumberGenerator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=255,
  serialized_end=478,
  methods=[
  _descriptor.MethodDescriptor(
    name='GenerateSequence',
    full_name='ablyStatefulServer.StatefulNumberGenerator.GenerateSequence',
    index=0,
    containing_service=None,
    input_type=_GENERATESEQUENCEREQUEST,
    output_type=_GENERATED,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReconnectSequence',
    full_name='ablyStatefulServer.StatefulNumberGenerator.ReconnectSequence',
    index=1,
    containing_service=None,
    input_type=_RECONNECTSEQUENCEREQUEST,
    output_type=_GENERATED,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STATEFULNUMBERGENERATOR)

DESCRIPTOR.services_by_name['StatefulNumberGenerator'] = _STATEFULNUMBERGENERATOR

# @@protoc_insertion_point(module_scope)
