// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/stateless/stateless.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenerateSequenceRequest struct {
	RestartFrom          uint32   `protobuf:"varint,1,opt,name=restartFrom,proto3" json:"restartFrom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateSequenceRequest) Reset()         { *m = GenerateSequenceRequest{} }
func (m *GenerateSequenceRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateSequenceRequest) ProtoMessage()    {}
func (*GenerateSequenceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8f24e3e7a9e3fd7, []int{0}
}

func (m *GenerateSequenceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateSequenceRequest.Unmarshal(m, b)
}
func (m *GenerateSequenceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateSequenceRequest.Marshal(b, m, deterministic)
}
func (m *GenerateSequenceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateSequenceRequest.Merge(m, src)
}
func (m *GenerateSequenceRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateSequenceRequest.Size(m)
}
func (m *GenerateSequenceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateSequenceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateSequenceRequest proto.InternalMessageInfo

func (m *GenerateSequenceRequest) GetRestartFrom() uint32 {
	if m != nil {
		return m.RestartFrom
	}
	return 0
}

type Generated struct {
	Number               uint32   `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Generated) Reset()         { *m = Generated{} }
func (m *Generated) String() string { return proto.CompactTextString(m) }
func (*Generated) ProtoMessage()    {}
func (*Generated) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8f24e3e7a9e3fd7, []int{1}
}

func (m *Generated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Generated.Unmarshal(m, b)
}
func (m *Generated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Generated.Marshal(b, m, deterministic)
}
func (m *Generated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Generated.Merge(m, src)
}
func (m *Generated) XXX_Size() int {
	return xxx_messageInfo_Generated.Size(m)
}
func (m *Generated) XXX_DiscardUnknown() {
	xxx_messageInfo_Generated.DiscardUnknown(m)
}

var xxx_messageInfo_Generated proto.InternalMessageInfo

func (m *Generated) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func init() {
	proto.RegisterType((*GenerateSequenceRequest)(nil), "ablyStatelessServer.GenerateSequenceRequest")
	proto.RegisterType((*Generated)(nil), "ablyStatelessServer.Generated")
}

func init() { proto.RegisterFile("protos/stateless/stateless.proto", fileDescriptor_c8f24e3e7a9e3fd7) }

var fileDescriptor_c8f24e3e7a9e3fd7 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x2f, 0x2e, 0x49, 0x2c, 0x49, 0xcd, 0x49, 0x2d, 0x46, 0x62, 0xe9, 0x81, 0xa5,
	0x84, 0x84, 0x13, 0x93, 0x72, 0x2a, 0x83, 0x61, 0x82, 0xc1, 0xa9, 0x45, 0x65, 0xa9, 0x45, 0x4a,
	0xd6, 0x5c, 0xe2, 0xee, 0xa9, 0x79, 0xa9, 0x45, 0x89, 0x25, 0xa9, 0xc1, 0xa9, 0x85, 0xa5, 0xa9,
	0x79, 0xc9, 0xa9, 0x41, 0x20, 0xba, 0xb8, 0x44, 0x48, 0x81, 0x8b, 0xbb, 0x28, 0xb5, 0xb8, 0x24,
	0xb1, 0xa8, 0xc4, 0xad, 0x28, 0x3f, 0x57, 0x82, 0x51, 0x81, 0x51, 0x83, 0x37, 0x08, 0x59, 0x48,
	0x49, 0x99, 0x8b, 0x13, 0xa6, 0x39, 0x45, 0x48, 0x8c, 0x8b, 0x2d, 0xaf, 0x34, 0x37, 0x29, 0xb5,
	0x08, 0xaa, 0x12, 0xca, 0x33, 0xaa, 0xe3, 0x92, 0x80, 0x5b, 0xea, 0x07, 0x16, 0x82, 0xea, 0xc9,
	0x2f, 0x12, 0x4a, 0xe2, 0x12, 0x40, 0xb7, 0x5d, 0x48, 0x47, 0x0f, 0x8b, 0x3b, 0xf5, 0x70, 0x38,
	0x52, 0x4a, 0x0e, 0xaf, 0xea, 0x14, 0x03, 0x46, 0x27, 0xf6, 0x28, 0x56, 0xb0, 0xff, 0x93, 0xd8,
	0xc0, 0x94, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x55, 0x66, 0xc8, 0x2a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StatelessNumberGeneratorClient is the client API for StatelessNumberGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatelessNumberGeneratorClient interface {
	GenerateSequence(ctx context.Context, in *GenerateSequenceRequest, opts ...grpc.CallOption) (StatelessNumberGenerator_GenerateSequenceClient, error)
}

type statelessNumberGeneratorClient struct {
	cc *grpc.ClientConn
}

func NewStatelessNumberGeneratorClient(cc *grpc.ClientConn) StatelessNumberGeneratorClient {
	return &statelessNumberGeneratorClient{cc}
}

func (c *statelessNumberGeneratorClient) GenerateSequence(ctx context.Context, in *GenerateSequenceRequest, opts ...grpc.CallOption) (StatelessNumberGenerator_GenerateSequenceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StatelessNumberGenerator_serviceDesc.Streams[0], "/ablyStatelessServer.StatelessNumberGenerator/GenerateSequence", opts...)
	if err != nil {
		return nil, err
	}
	x := &statelessNumberGeneratorGenerateSequenceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StatelessNumberGenerator_GenerateSequenceClient interface {
	Recv() (*Generated, error)
	grpc.ClientStream
}

type statelessNumberGeneratorGenerateSequenceClient struct {
	grpc.ClientStream
}

func (x *statelessNumberGeneratorGenerateSequenceClient) Recv() (*Generated, error) {
	m := new(Generated)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StatelessNumberGeneratorServer is the server API for StatelessNumberGenerator service.
type StatelessNumberGeneratorServer interface {
	GenerateSequence(*GenerateSequenceRequest, StatelessNumberGenerator_GenerateSequenceServer) error
}

// UnimplementedStatelessNumberGeneratorServer can be embedded to have forward compatible implementations.
type UnimplementedStatelessNumberGeneratorServer struct {
}

func (*UnimplementedStatelessNumberGeneratorServer) GenerateSequence(req *GenerateSequenceRequest, srv StatelessNumberGenerator_GenerateSequenceServer) error {
	return status.Errorf(codes.Unimplemented, "method GenerateSequence not implemented")
}

func RegisterStatelessNumberGeneratorServer(s *grpc.Server, srv StatelessNumberGeneratorServer) {
	s.RegisterService(&_StatelessNumberGenerator_serviceDesc, srv)
}

func _StatelessNumberGenerator_GenerateSequence_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateSequenceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StatelessNumberGeneratorServer).GenerateSequence(m, &statelessNumberGeneratorGenerateSequenceServer{stream})
}

type StatelessNumberGenerator_GenerateSequenceServer interface {
	Send(*Generated) error
	grpc.ServerStream
}

type statelessNumberGeneratorGenerateSequenceServer struct {
	grpc.ServerStream
}

func (x *statelessNumberGeneratorGenerateSequenceServer) Send(m *Generated) error {
	return x.ServerStream.SendMsg(m)
}

var _StatelessNumberGenerator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ablyStatelessServer.StatelessNumberGenerator",
	HandlerType: (*StatelessNumberGeneratorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerateSequence",
			Handler:       _StatelessNumberGenerator_GenerateSequence_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/stateless/stateless.proto",
}
