// Code generated by protoc-gen-go. DO NOT EDIT.
// source: statefulProto/stateful.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenerateSequenceRequest struct {
	ConnectionID         string   `protobuf:"bytes,1,opt,name=connectionID,proto3" json:"connectionID,omitempty"`
	SequenceLength       uint32   `protobuf:"varint,2,opt,name=sequenceLength,proto3" json:"sequenceLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateSequenceRequest) Reset()         { *m = GenerateSequenceRequest{} }
func (m *GenerateSequenceRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateSequenceRequest) ProtoMessage()    {}
func (*GenerateSequenceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75425868e93fcb8, []int{0}
}

func (m *GenerateSequenceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateSequenceRequest.Unmarshal(m, b)
}
func (m *GenerateSequenceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateSequenceRequest.Marshal(b, m, deterministic)
}
func (m *GenerateSequenceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateSequenceRequest.Merge(m, src)
}
func (m *GenerateSequenceRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateSequenceRequest.Size(m)
}
func (m *GenerateSequenceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateSequenceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateSequenceRequest proto.InternalMessageInfo

func (m *GenerateSequenceRequest) GetConnectionID() string {
	if m != nil {
		return m.ConnectionID
	}
	return ""
}

func (m *GenerateSequenceRequest) GetSequenceLength() uint32 {
	if m != nil {
		return m.SequenceLength
	}
	return 0
}

type ReconnectSequenceRequest struct {
	ConnectionID         string   `protobuf:"bytes,1,opt,name=connectionID,proto3" json:"connectionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReconnectSequenceRequest) Reset()         { *m = ReconnectSequenceRequest{} }
func (m *ReconnectSequenceRequest) String() string { return proto.CompactTextString(m) }
func (*ReconnectSequenceRequest) ProtoMessage()    {}
func (*ReconnectSequenceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75425868e93fcb8, []int{1}
}

func (m *ReconnectSequenceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReconnectSequenceRequest.Unmarshal(m, b)
}
func (m *ReconnectSequenceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReconnectSequenceRequest.Marshal(b, m, deterministic)
}
func (m *ReconnectSequenceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReconnectSequenceRequest.Merge(m, src)
}
func (m *ReconnectSequenceRequest) XXX_Size() int {
	return xxx_messageInfo_ReconnectSequenceRequest.Size(m)
}
func (m *ReconnectSequenceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReconnectSequenceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReconnectSequenceRequest proto.InternalMessageInfo

func (m *ReconnectSequenceRequest) GetConnectionID() string {
	if m != nil {
		return m.ConnectionID
	}
	return ""
}

type Generated struct {
	Number               uint32   `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	FinalItem            bool     `protobuf:"varint,2,opt,name=finalItem,proto3" json:"finalItem,omitempty"`
	Checksum             uint32   `protobuf:"varint,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Generated) Reset()         { *m = Generated{} }
func (m *Generated) String() string { return proto.CompactTextString(m) }
func (*Generated) ProtoMessage()    {}
func (*Generated) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75425868e93fcb8, []int{2}
}

func (m *Generated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Generated.Unmarshal(m, b)
}
func (m *Generated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Generated.Marshal(b, m, deterministic)
}
func (m *Generated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Generated.Merge(m, src)
}
func (m *Generated) XXX_Size() int {
	return xxx_messageInfo_Generated.Size(m)
}
func (m *Generated) XXX_DiscardUnknown() {
	xxx_messageInfo_Generated.DiscardUnknown(m)
}

var xxx_messageInfo_Generated proto.InternalMessageInfo

func (m *Generated) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Generated) GetFinalItem() bool {
	if m != nil {
		return m.FinalItem
	}
	return false
}

func (m *Generated) GetChecksum() uint32 {
	if m != nil {
		return m.Checksum
	}
	return 0
}

func init() {
	proto.RegisterType((*GenerateSequenceRequest)(nil), "ablyStatefulServer.GenerateSequenceRequest")
	proto.RegisterType((*ReconnectSequenceRequest)(nil), "ablyStatefulServer.ReconnectSequenceRequest")
	proto.RegisterType((*Generated)(nil), "ablyStatefulServer.Generated")
}

func init() { proto.RegisterFile("statefulProto/stateful.proto", fileDescriptor_e75425868e93fcb8) }

var fileDescriptor_e75425868e93fcb8 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x2e, 0x49, 0x2c,
	0x49, 0x4d, 0x2b, 0xcd, 0x09, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x87, 0xf1, 0xf4, 0x0a, 0x40, 0x5c,
	0x21, 0xa1, 0xc4, 0xa4, 0x9c, 0xca, 0x60, 0xa8, 0x58, 0x70, 0x6a, 0x51, 0x59, 0x6a, 0x91, 0x52,
	0x2a, 0x97, 0xb8, 0x7b, 0x6a, 0x5e, 0x6a, 0x51, 0x62, 0x49, 0x6a, 0x70, 0x6a, 0x61, 0x69, 0x6a,
	0x5e, 0x72, 0x6a, 0x10, 0x88, 0x2e, 0x2e, 0x11, 0x52, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcb, 0x4b,
	0x4d, 0x2e, 0xc9, 0xcc, 0xcf, 0xf3, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x42, 0x11,
	0x13, 0x52, 0xe3, 0xe2, 0x2b, 0x86, 0x6a, 0xf3, 0x49, 0xcd, 0x4b, 0x2f, 0xc9, 0x90, 0x60, 0x52,
	0x60, 0xd4, 0xe0, 0x0d, 0x42, 0x13, 0x55, 0xb2, 0xe3, 0x92, 0x08, 0x4a, 0x85, 0xea, 0x24, 0xc3,
	0x1e, 0xa5, 0x58, 0x2e, 0x4e, 0x98, 0x33, 0x53, 0x84, 0xc4, 0xb8, 0xd8, 0xf2, 0x4a, 0x73, 0x93,
	0x52, 0x8b, 0xc0, 0x4a, 0x79, 0x83, 0xa0, 0x3c, 0x21, 0x19, 0x2e, 0xce, 0xb4, 0xcc, 0xbc, 0xc4,
	0x1c, 0xcf, 0x92, 0xd4, 0x5c, 0xb0, 0x3b, 0x38, 0x82, 0x10, 0x02, 0x42, 0x52, 0x5c, 0x1c, 0xc9,
	0x19, 0xa9, 0xc9, 0xd9, 0xc5, 0xa5, 0xb9, 0x12, 0xcc, 0x60, 0x7d, 0x70, 0xbe, 0xd1, 0x7d, 0x46,
	0x2e, 0x71, 0x58, 0xc0, 0xf8, 0x81, 0x0d, 0x83, 0xda, 0x96, 0x5f, 0x24, 0x94, 0xc0, 0x25, 0x80,
	0x1e, 0x42, 0x42, 0xda, 0x7a, 0x98, 0x41, 0xa9, 0x87, 0x23, 0x1c, 0xa5, 0x64, 0xf1, 0x29, 0x4e,
	0x31, 0x60, 0x14, 0x4a, 0xe2, 0x12, 0xc4, 0x08, 0x1c, 0x21, 0x1d, 0x6c, 0xba, 0x70, 0x85, 0x21,
	0x41, 0x3b, 0x9c, 0xd8, 0xa3, 0x58, 0xc1, 0x89, 0x20, 0x89, 0x0d, 0x4c, 0x19, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x27, 0x9f, 0xc9, 0x8c, 0x2b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StatefulNumberGeneratorClient is the client API for StatefulNumberGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatefulNumberGeneratorClient interface {
	GenerateSequence(ctx context.Context, in *GenerateSequenceRequest, opts ...grpc.CallOption) (StatefulNumberGenerator_GenerateSequenceClient, error)
	ReconnectSequence(ctx context.Context, in *ReconnectSequenceRequest, opts ...grpc.CallOption) (StatefulNumberGenerator_ReconnectSequenceClient, error)
}

type statefulNumberGeneratorClient struct {
	cc *grpc.ClientConn
}

func NewStatefulNumberGeneratorClient(cc *grpc.ClientConn) StatefulNumberGeneratorClient {
	return &statefulNumberGeneratorClient{cc}
}

func (c *statefulNumberGeneratorClient) GenerateSequence(ctx context.Context, in *GenerateSequenceRequest, opts ...grpc.CallOption) (StatefulNumberGenerator_GenerateSequenceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StatefulNumberGenerator_serviceDesc.Streams[0], "/ablyStatefulServer.StatefulNumberGenerator/GenerateSequence", opts...)
	if err != nil {
		return nil, err
	}
	x := &statefulNumberGeneratorGenerateSequenceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StatefulNumberGenerator_GenerateSequenceClient interface {
	Recv() (*Generated, error)
	grpc.ClientStream
}

type statefulNumberGeneratorGenerateSequenceClient struct {
	grpc.ClientStream
}

func (x *statefulNumberGeneratorGenerateSequenceClient) Recv() (*Generated, error) {
	m := new(Generated)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *statefulNumberGeneratorClient) ReconnectSequence(ctx context.Context, in *ReconnectSequenceRequest, opts ...grpc.CallOption) (StatefulNumberGenerator_ReconnectSequenceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StatefulNumberGenerator_serviceDesc.Streams[1], "/ablyStatefulServer.StatefulNumberGenerator/ReconnectSequence", opts...)
	if err != nil {
		return nil, err
	}
	x := &statefulNumberGeneratorReconnectSequenceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StatefulNumberGenerator_ReconnectSequenceClient interface {
	Recv() (*Generated, error)
	grpc.ClientStream
}

type statefulNumberGeneratorReconnectSequenceClient struct {
	grpc.ClientStream
}

func (x *statefulNumberGeneratorReconnectSequenceClient) Recv() (*Generated, error) {
	m := new(Generated)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StatefulNumberGeneratorServer is the server API for StatefulNumberGenerator service.
type StatefulNumberGeneratorServer interface {
	GenerateSequence(*GenerateSequenceRequest, StatefulNumberGenerator_GenerateSequenceServer) error
	ReconnectSequence(*ReconnectSequenceRequest, StatefulNumberGenerator_ReconnectSequenceServer) error
}

// UnimplementedStatefulNumberGeneratorServer can be embedded to have forward compatible implementations.
type UnimplementedStatefulNumberGeneratorServer struct {
}

func (*UnimplementedStatefulNumberGeneratorServer) GenerateSequence(req *GenerateSequenceRequest, srv StatefulNumberGenerator_GenerateSequenceServer) error {
	return status.Errorf(codes.Unimplemented, "method GenerateSequence not implemented")
}
func (*UnimplementedStatefulNumberGeneratorServer) ReconnectSequence(req *ReconnectSequenceRequest, srv StatefulNumberGenerator_ReconnectSequenceServer) error {
	return status.Errorf(codes.Unimplemented, "method ReconnectSequence not implemented")
}

func RegisterStatefulNumberGeneratorServer(s *grpc.Server, srv StatefulNumberGeneratorServer) {
	s.RegisterService(&_StatefulNumberGenerator_serviceDesc, srv)
}

func _StatefulNumberGenerator_GenerateSequence_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateSequenceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StatefulNumberGeneratorServer).GenerateSequence(m, &statefulNumberGeneratorGenerateSequenceServer{stream})
}

type StatefulNumberGenerator_GenerateSequenceServer interface {
	Send(*Generated) error
	grpc.ServerStream
}

type statefulNumberGeneratorGenerateSequenceServer struct {
	grpc.ServerStream
}

func (x *statefulNumberGeneratorGenerateSequenceServer) Send(m *Generated) error {
	return x.ServerStream.SendMsg(m)
}

func _StatefulNumberGenerator_ReconnectSequence_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReconnectSequenceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StatefulNumberGeneratorServer).ReconnectSequence(m, &statefulNumberGeneratorReconnectSequenceServer{stream})
}

type StatefulNumberGenerator_ReconnectSequenceServer interface {
	Send(*Generated) error
	grpc.ServerStream
}

type statefulNumberGeneratorReconnectSequenceServer struct {
	grpc.ServerStream
}

func (x *statefulNumberGeneratorReconnectSequenceServer) Send(m *Generated) error {
	return x.ServerStream.SendMsg(m)
}

var _StatefulNumberGenerator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ablyStatefulServer.StatefulNumberGenerator",
	HandlerType: (*StatefulNumberGeneratorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerateSequence",
			Handler:       _StatefulNumberGenerator_GenerateSequence_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReconnectSequence",
			Handler:       _StatefulNumberGenerator_ReconnectSequence_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "statefulProto/stateful.proto",
}
